---
- name: Copy the config file to "host" windows machine
  win_copy:
    src: config_files/.kube/config
    dest: C:\path\to\destination\file  # Path to the file on the destination host
    delegate_to: destination_host 