---
- name: Install vagrant
  win_chocolatey:
    name: vagrant
    version: "{{ vagrant_version }}"
    state: present
- name: Copy vagrant file to windows remote
  ansible.windows.win_template:
    src: templates/vagrantfile/vagrantfile.conf.j2
    dest: "{{ windows_userprofile_dir_vagrantfile }}\\vagrantfile"
- name: Run Vagrant
  ansible.windows.win_powershell:
    script: vagrant up
    chdir: "{{ windows_userprofile_dir_vagrantfile }}"
#- win_command: powershell.exe -
#  args: 
#    stdin: vagrant up
#  become: true
#  become_user: Administrator