---
#Remote windows installation
- name: Install VirtualBox on Windows
  hosts: win
  gather_facts: false

  roles:
    - windows
    - vagrant

- name: Install Kubernetes Core
  hosts: k8scluster
  become: true
  roles:
#    - ubuntu_update
    - kubernetes_core