---
- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: "{{ chocolatey_version }}"
- name: Install VirtualBox using Chocolatey
  win_chocolatey:
    name: virtualbox
    state: "{{ virtualbox_version }}"
- name: Install python311
  win_chocolatey:
    name: python311
    version: "{{ python_version }}"
    state: present