---
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
- name: Upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes
- name: Check if a reboot is needed on all servers
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=n
- name: Reboot the box if kernel updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when: reboot_required_file.stat.exists
#- name: Set the all hostnames
#  hostname:
#    name: " {{ ansible_hostname }} "
- name: Adding hosts entries to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      k8s-master {{ hostvars[ 'k8s-master' ].ansible_eth1.ipv4.address }}
      node-1 {{ hostvars[ 'node-1' ].ansible_eth1.ipv4.address }}
      node-2 {{ hostvars[ 'node-2' ].ansible_eth1.ipv4.address }}
- name: Load Kernel module overlay
  community.general.modprobe:
    name: overlay
    state: present
- name: Load kernel module br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present 
- name: Set iptables for kubernetes
  blockinfile:
    path: /etc/sysctl.d/kubernetes.conf
    create: true
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
- name: Take effect of new settings for sysctl
  shell: sysctl --system